version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: --smallfiles
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/devcollab
      - NODE_ENV=development
    volumes:
      - ./backend:/backend
    command: npm run dev
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    command: npm start